
ALTER TABLE trCardInfo
ADD COLUMN `machine_id` varchar(200) COLLATE utf8_unicode_ci NOT NULL


ALTER TABLE `trCardInfo`
ADD PRIMARY KEY (`id`);

ALTER TABLE `trCardInfo`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;