ALTER TABLE `trrunbatch` ADD PRIMARY KEY(`id`);
ALTER TABLE `trrunbatch`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trrigconfig` ADD PRIMARY KEY(`id`);
ALTER TABLE `trrigconfig`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trrigevent` ADD PRIMARY KEY(`id`);
ALTER TABLE `trrigevent`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trrigsoftwaredownload` ADD PRIMARY KEY(`id`);
ALTER TABLE `trrigsoftwaredownload`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trorder` ADD PRIMARY KEY(`id`);
ALTER TABLE `trorder`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `truser` ADD PRIMARY KEY(`id`);
ALTER TABLE `truser`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trsocketmobileinfo` ADD PRIMARY KEY(`id`);
ALTER TABLE `trsocketmobileinfo`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trrole` ADD PRIMARY KEY(`id`);
ALTER TABLE `trrole`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trloadrig` ADD PRIMARY KEY(`id`);
ALTER TABLE `trloadrig`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trdownloadlink` ADD PRIMARY KEY(`id`);
ALTER TABLE `trdownloadlink`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trconfig` ADD PRIMARY KEY(`id`);
ALTER TABLE `trconfig`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trcardinfo` ADD PRIMARY KEY(`id`);
ALTER TABLE `trcardinfo`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trauthwebfrontend` ADD PRIMARY KEY(`id`);
ALTER TABLE `trauthwebfrontend`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `trauthrig` ADD PRIMARY KEY(`id`);
ALTER TABLE `trauthrig`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;